In [1]:
import pandas as pd
import numpy as np
import transformers
from transformers import AutoTokenizer, AutoModelForTokenClassification, pipeline

In [3]:
import evaluate

In [18]:


ds = load_dataset("fancyzhx/ag_news")

In [25]:
train_dataset = ds['train']
test_dataset = ds['test']

In [26]:
train_ds = pd.DataFrame(train_dataset)
test_ds = pd.DataFrame(test_dataset)

In [166]:
train_ds

                                                     text  label
0       Wall St. Bears Claw Back Into the Black (Reute...      2
1       Carlyle Looks Toward Commercial Aerospace (Reu...      2
2       Oil and Economy Cloud Stocks' Outlook (Reuters...      2
3       Iraq Halts Oil Exports from Main Southern Pipe...      2
4       Oil prices soar to all-time record, posing new...      2
...                                                   ...    ...
119995  Pakistan's Musharraf Says Won't Quit as Army C...      0
119996  Renteria signing a top-shelf deal Red Sox gene...      1
119997  Saban not going to Dolphins yet The Miami Dolp...      1
119998  Today's NFL games PITTSBURGH at NY GIANTS Time...      1
119999  Nets get Carter from Raptors INDIANAPOLIS -- A...      1

[120000 rows x 2 columns]

In [27]:
train_ds['label'].unique()

# 0 = world
# 1 = sports
# 2 = buisness
# 3 = tech

array([2, 3, 1, 0])

In [45]:
label = train_ds['label']

In [56]:
ds_world = train_ds[(label == 0)][:10]
ds_sports = train_ds[(label == 1)][:10]
ds_buisness = train_ds[(label == 2)][:10]
ds_tech = train_ds[(label == 3)][:10]

In [58]:
new_ds = pd.DataFrame()

In [63]:
new_ds = pd.concat([ds_world, ds_sports, ds_buisness, ds_tech])

In [66]:
new_ds = new_ds.sample(frac=1).reset_index(drop=True)

In [172]:
dataset = new_ds.copy()
new_ds['label'] = new_ds['label'].map({ 0 : 'world' , 1 : 'sport', 2 : 'buisness', 3 : 'tech'})

In [174]:
new_ds[:10]

                                                text     label
0  AOL to Sell Cheap PCs to Minorities and Senior...      tech
1  Rwanda Troops Airlifted to Start AU Mission in...     world
2  Carlyle Looks Toward Commercial Aerospace (Reu...  buisness
3  S.Koreans Clash with Police on Iraq Troop Disp...     world
4  Hacker Cracks Apple's Streaming Technology (AP...      tech
5  Iraq Halts Oil Exports from Main Southern Pipe...  buisness
6  Sun's Looking Glass Provides 3D View (PC World...      tech
7  Dreaming done, NBA stars awaken to harsh Olymp...     sport
8  Kerry Campaign Helping With Fla. Recovery (AP)...     world
9  Oracle Sales Data Seen Being Released (Reuters...      tech

In [86]:
classifier_1 = pipeline(
    "text-classification",
    model="Sengil/ModernBERT-NewsClassifier-EN-small",
    device = 0
)

Loading weights:   0%|          | 0/138 [00:00<?, ?it/s]

In [185]:
for row in new_ds[:10].itertuples():
    text = row.text
    label = row.label
    outputs = classifier_1(text)
    print(f'Результат модели : {outputs}, метка сета: {label}' )

Результат модели : [{'label': 'BUSINESS', 'score': 0.9518128037452698}], метка сета: tech
Результат модели : [{'label': 'POLITICS', 'score': 0.9835475087165833}], метка сета: world
Результат модели : [{'label': 'BUSINESS', 'score': 0.9947249293327332}], метка сета: buisness
Результат модели : [{'label': 'POLITICS', 'score': 0.9848883152008057}], метка сета: world
Результат модели : [{'label': 'BUSINESS', 'score': 0.836663544178009}], метка сета: tech
Результат модели : [{'label': 'POLITICS', 'score': 0.5044594407081604}], метка сета: buisness
Результат модели : [{'label': 'BUSINESS', 'score': 0.6961901783943176}], метка сета: tech
Результат модели : [{'label': 'SPORTS', 'score': 0.9893108606338501}], метка сета: sport
Результат модели : [{'label': 'POLITICS', 'score': 0.9837439656257629}], метка сета: world
Результат модели : [{'label': 'BUSINESS', 'score': 0.9964865446090698}], метка сета: tech

In [136]:
classifier_2 = pipeline(
    "text-classification",
    model="Asphate/nanoclass-bbc",
    device = 0
)

Loading weights:   0%|          | 0/104 [00:00<?, ?it/s]

In [186]:
for row in new_ds[:10].itertuples():
    text = row.text
    label = row.label
    outputs = classifier_2(text)
    print(f'Результат модели : {outputs}, метка сета: {label}' )

Результат модели : [{'label': 'business', 'score': 0.9993323683738708}], метка сета: tech
Результат модели : [{'label': 'business', 'score': 0.984890878200531}], метка сета: world
Результат модели : [{'label': 'business', 'score': 0.999528169631958}], метка сета: buisness
Результат модели : [{'label': 'business', 'score': 0.9553015232086182}], метка сета: world
Результат модели : [{'label': 'tech', 'score': 0.999488353729248}], метка сета: tech
Результат модели : [{'label': 'business', 'score': 0.9994751811027527}], метка сета: buisness
Результат модели : [{'label': 'tech', 'score': 0.9993926286697388}], метка сета: tech
Результат модели : [{'label': 'sport', 'score': 0.9994526505470276}], метка сета: sport
Результат модели : [{'label': 'politics', 'score': 0.9622747302055359}], метка сета: world
Результат модели : [{'label': 'business', 'score': 0.998087465763092}], метка сета: tech

In [162]:
classifier_3 = pipeline(
    "text-classification",
    model="Ginidu2003/Distilbert-Base-News-classifier",
    device = 0
)

Loading weights:   0%|          | 0/104 [00:00<?, ?it/s]

In [187]:
for row in new_ds[:10].itertuples():
    text = row.text
    label = row.label
    outputs = classifier_3(text)
    print(f'Результат модели : {outputs}, метка сета: {label}' )

Результат модели : [{'label': 'World news', 'score': 0.9795570373535156}], метка сета: tech
Результат модели : [{'label': 'World news', 'score': 0.9892086386680603}], метка сета: world
Результат модели : [{'label': 'Business', 'score': 0.9490109086036682}], метка сета: buisness
Результат модели : [{'label': 'World news', 'score': 0.9961070418357849}], метка сета: world
Результат модели : [{'label': 'World news', 'score': 0.9950492978096008}], метка сета: tech
Результат модели : [{'label': 'World news', 'score': 0.9962149262428284}], метка сета: buisness
Результат модели : [{'label': 'Business', 'score': 0.9488088488578796}], метка сета: tech
Результат модели : [{'label': 'Sports', 'score': 0.9909084439277649}], метка сета: sport
Результат модели : [{'label': 'World news', 'score': 0.9913683533668518}], метка сета: world
Результат модели : [{'label': 'World news', 'score': 0.9849145412445068}], метка сета: tech

In [4]:
sport_news = '''Dexter Lawrence’s new chapter in the NFL has begun, and he admitted for the first time since the
                New York Giants traded him to the Cincinnati Bengals that he has a "fire in me that I’ve never had before."

The Giants fulfilled Lawrence’s trade request on Saturday, sending the three-time Pro Bowl defensive tackle to the Bengals 
in exchange for the No. 10 overall pick in the 2026 NFL Draft — a blockbuster deal that changes things in the first round 
set to kick off from Pittsburgh on Thursday night.

Lawrence was the 17th overall pick of the 2019 draft, and he quickly became a fan-favorite for the Giants as well 
as arguably the best interior defensive lineman in the NFL'''

sport_news_2 = '''Two UFC fighters can thank President Donald Trump for getting onto the card for the White House event two months from now.

Trump was at UFC 327 in Miami on Saturday night as a special guest of UFC president Dana White, 
marking his first appearance at a pro sporting event since the beginning of the Iran war.

During the event, UFC added a bout between Derrick Lewis and Josh Hokit for UFC Freedom 250,
and Dana White said the bout was prompted by Trump.'''

buisness_news_1 =  '''Walmart announced that it's planning to remodel more than 650 of its stores around the U.S.
while it also will open about 20 new stores in 2026 and early 2027.

The retail giant said on Thursday that the plan builds on its 2024 commitment to open or convert over 150 new locations 
while updating its existing store portfolio.

"This investment is intended to create jobs, help strengthen local economies, and make shopping faster and more convenient
for our customers," Walmart said, adding that the new stores and 
remodels will drive construction jobs during the projects while creating long-term roles in retail, pharmacy and store leadership.'''

In [190]:
outputs_classifier_1 = classifier_1(sport_news)
outputs_classifier_2 = classifier_2(sport_news)
outputs_classifier_3 = classifier_3(sport_news)
print(f'Вывод модели {outputs_classifier_1}, Реальная метка:  [Sport] ')
print(f'Вывод модели {outputs_classifier_2}, Реальная метка:  [Sport] ')
print(f'Вывод модели {outputs_classifier_3}, Реальная метка:  [Sport] ')

Вывод модели [{'label': 'SPORTS', 'score': 0.9893001317977905}], Реальная метка:  [Sport]
Вывод модели [{'label': 'sport', 'score': 0.9993601441383362}], Реальная метка:  [Sport]
Вывод модели [{'label': 'Sports', 'score': 0.9536307454109192}], Реальная метка:  [Sport]

In [192]:
outputs_classifier_1_2 = classifier_1(sport_news_2)
outputs_classifier_2_2 = classifier_2(sport_news_2)
outputs_classifier_3_2 = classifier_3(sport_news_2)
print(f'Вывод модели {outputs_classifier_1_2}, Реальная метка:  [Sport] ')
print(f'Вывод модели {outputs_classifier_2_2}, Реальная метка:  [Sport] ')
print(f'Вывод модели {outputs_classifier_3_2}, Реальная метка:  [Sport] ')

Вывод модели [{'label': 'SPORTS', 'score': 0.794918417930603}], Реальная метка:  [Sport]
Вывод модели [{'label': 'sport', 'score': 0.9951039552688599}], Реальная метка:  [Sport]
Вывод модели [{'label': 'World news', 'score': 0.9901719689369202}], Реальная метка:  [Sport]

In [ ]:
#Summarization

In [55]:
rouge_score = evaluate.load('rouge')
bleu_score = evaluate.load('bleu')

Downloading builder script: 0.00B [00:00, ?B/s]

Downloading extra modules:   0%|          | 0.00/1.55k [00:00<?, ?B/s]

Downloading extra modules: 0.00B [00:00, ?B/s]

In [33]:
summarizer_1 = pipeline("summarization", model="facebook/bart-large-cnn")

In [11]:
summarizer_2 = pipeline("summarization", model="sshleifer/distilbart-xsum-1-1", device = 0)

In [18]:
summarizer_3 = pipeline("summarization", model="knkarthick/MEETING_SUMMARY")

In [58]:
outputs_summarizer_1_1 = summarizer_1(sport_news)
outputs_summarizer_1_2 = summarizer_1(sport_news_2)
outputs_summarizer_1_3 = summarizer_1(buisness_news_1)
rouge_scores_1_1 = rouge_score.compute(predictions = [outputs_summarizer_1_1[0]['summary_text']], references = [sport_news])
rouge_scores_1_2 = rouge_score.compute(predictions = [outputs_summarizer_1_2[0]['summary_text']], references = [sport_news_2])
rouge_scores_1_3 = rouge_score.compute(predictions = [outputs_summarizer_1_3[0]['summary_text']], references = [buisness_news_1])
bleu_scores_1_1 = bleu_score.compute(predictions = [outputs_summarizer_1_1[0]['summary_text']], references = [sport_news])
bleu_scores_1_2 = bleu_score.compute(predictions = [outputs_summarizer_1_2[0]['summary_text']], references = [sport_news_2])
bleu_scores_1_3 = bleu_score.compute(predictions = [outputs_summarizer_1_3[0]['summary_text']], references = [buisness_news_1])

Your max_length is set to 142, but your input_length is only 101. Since this is a summarization task, where outputs shorter than the input are typically wanted, you might consider decreasing max_length manually, e.g. summarizer('...', max_length=50)
Your max_length is set to 142, but your input_length is only 137. Since this is a summarization task, where outputs shorter than the input are typically wanted, you might consider decreasing max_length manually, e.g. summarizer('...', max_length=68)

In [60]:
outputs_summarizer_2_1 = summarizer_2(sport_news)
outputs_summarizer_2_2 = summarizer_2(sport_news_2)
outputs_summarizer_2_3 = summarizer_2(buisness_news_1)
rouge_scores_2_1 = rouge_score.compute(predictions = [outputs_summarizer_2_1[0]['summary_text']], references = [sport_news])
rouge_scores_2_2 = rouge_score.compute(predictions = [outputs_summarizer_2_2[0]['summary_text']], references = [sport_news_2])
rouge_scores_2_3 = rouge_score.compute(predictions = [outputs_summarizer_2_3[0]['summary_text']], references = [buisness_news_1])
bleu_scores_2_1 = bleu_score.compute(predictions = [outputs_summarizer_2_1[0]['summary_text']], references = [sport_news])
bleu_scores_2_2 = bleu_score.compute(predictions = [outputs_summarizer_2_2[0]['summary_text']], references = [sport_news_2])
bleu_scores_2_3 = bleu_score.compute(predictions = [outputs_summarizer_2_3[0]['summary_text']], references = [buisness_news_1])

In [61]:
outputs_summarizer_3_1 = summarizer_3(sport_news)
outputs_summarizer_3_2 = summarizer_3(sport_news_2)
outputs_summarizer_3_3 = summarizer_3(buisness_news_1)
rouge_scores_3_1 = rouge_score.compute(predictions = [outputs_summarizer_3_1[0]['summary_text']], references = [sport_news])
rouge_scores_3_2 = rouge_score.compute(predictions = [outputs_summarizer_3_2[0]['summary_text']], references = [sport_news_2])
rouge_scores_3_3 = rouge_score.compute(predictions = [outputs_summarizer_3_3[0]['summary_text']], references = [buisness_news_1])
bleu_scores_3_1 = bleu_score.compute(predictions = [outputs_summarizer_3_1[0]['summary_text']], references = [sport_news])
bleu_scores_3_2 = bleu_score.compute(predictions = [outputs_summarizer_3_2[0]['summary_text']], references = [sport_news_2])
bleu_scores_3_3 = bleu_score.compute(predictions = [outputs_summarizer_3_3[0]['summary_text']], references = [buisness_news_1])

In [127]:
summarizer_list = ['bart-large-cnn', 'distilbart-xsum-1-1', 'MEETING_SUMMARY']
text_list = ['sport_news', 'sport_news_2', 'buisness_news']

rouge_scor = [
    rouge_scores_1_1['rouge1'], rouge_scores_1_1['rouge2'],
    rouge_scores_1_2['rouge1'], rouge_scores_1_2['rouge2'],
    rouge_scores_1_3['rouge1'], rouge_scores_1_3['rouge2'],
    rouge_scores_2_1['rouge1'], rouge_scores_2_1['rouge2'],
    rouge_scores_2_2['rouge1'], rouge_scores_2_2['rouge2'],
    rouge_scores_2_3['rouge1'], rouge_scores_2_3['rouge2'],
    rouge_scores_3_1['rouge1'], rouge_scores_3_1['rouge2'],
    rouge_scores_3_2['rouge1'], rouge_scores_3_2['rouge2'],
    rouge_scores_3_3['rouge1'], rouge_scores_3_3['rouge2']
    
             ] 
bleu_scor = [
    bleu_scores_1_1['bleu'], bleu_scores_1_1['precisions'],
    bleu_scores_1_2['bleu'], bleu_scores_1_2['precisions'],
    bleu_scores_1_3['bleu'], bleu_scores_1_3['precisions'],
    bleu_scores_2_1['bleu'], bleu_scores_2_1['precisions'],
    bleu_scores_2_2['bleu'], bleu_scores_2_2['precisions'],
    bleu_scores_2_3['bleu'], bleu_scores_2_3['precisions'],
    bleu_scores_3_1['bleu'], bleu_scores_3_1['precisions'],
    bleu_scores_3_2['bleu'], bleu_scores_3_2['precisions'],
    bleu_scores_3_3['bleu'], bleu_scores_3_3['precisions']
]

In [129]:
idx = 0
for summar in summarizer_list:
    for text in text_list:
        rouge1 = rouge_scor[idx]     
        rouge2 = rouge_scor[idx + 1] 
        bleu = bleu_scor[idx]
        bleu_precision = bleu_scor[idx + 1]
        print(f'Модель: {summar}, Текст : {text}. rouge: {rouge1:.2f}, rouge2: {rouge2:.2f}')
        print(f'Модель: {summar}, Текст : {text}.  bleu: {bleu:.2f}, bleu_precision: {[f'{prec:.2f}' for prec in bleu_precision]}')
        idx += 2

Модель: bart-large-cnn, Текст : sport_news. rouge: 0.52, rouge2: 0.42
Модель: bart-large-cnn, Текст : sport_news.  bleu: 0.13, bleu_precision: ['0.92', '0.69', '0.56', '0.47']
Модель: bart-large-cnn, Текст : sport_news_2. rouge: 0.80, rouge2: 0.75
Модель: bart-large-cnn, Текст : sport_news_2.  bleu: 0.57, bleu_precision: ['0.97', '0.90', '0.85', '0.80']
Модель: bart-large-cnn, Текст : buisness_news. rouge: 0.74, rouge2: 0.68
Модель: bart-large-cnn, Текст : buisness_news.  bleu: 0.49, bleu_precision: ['0.97', '0.89', '0.84', '0.78']
Модель: distilbart-xsum-1-1, Текст : sport_news. rouge: 0.12, rouge2: 0.03
Модель: distilbart-xsum-1-1, Текст : sport_news.  bleu: 0.00, bleu_precision: ['0.75', '0.18', '0.00', '0.00']
Модель: distilbart-xsum-1-1, Текст : sport_news_2. rouge: 0.08, rouge2: 0.00
Модель: distilbart-xsum-1-1, Текст : sport_news_2.  bleu: 0.00, bleu_precision: ['0.29', '0.00', '0.00', '0.00']
Модель: distilbart-xsum-1-1, Текст : buisness_news. rouge: 0.14, rouge2: 0.00
Модель: distilbart-xsum-1-1, Текст : buisness_news.  bleu: 0.00, bleu_precision: ['0.50', '0.00', '0.00', '0.00']
Модель: MEETING_SUMMARY, Текст : sport_news. rouge: 0.37, rouge2: 0.28
Модель: MEETING_SUMMARY, Текст : sport_news.  bleu: 0.02, bleu_precision: ['1.00', '0.72', '0.57', '0.48']
Модель: MEETING_SUMMARY, Текст : sport_news_2. rouge: 0.41, rouge2: 0.36
Модель: MEETING_SUMMARY, Текст : sport_news_2.  bleu: 0.05, bleu_precision: ['0.92', '0.83', '0.77', '0.71']
Модель: MEETING_SUMMARY, Текст : buisness_news. rouge: 0.31, rouge2: 0.22
Модель: MEETING_SUMMARY, Текст : buisness_news.  bleu: 0.01, bleu_precision: ['0.91', '0.64', '0.52', '0.45']

In [16]:
from transformers import AutoTokenizer, AutoModelForTokenClassification, pipeline

model_name = "Davlan/bert-base-multilingual-cased-ner-hrl"
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForTokenClassification.from_pretrained(model_name)
nlp = pipeline("ner", model=model, tokenizer=tokenizer, device=-1)

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

BertForTokenClassification LOAD REPORT from: Davlan/bert-base-multilingual-cased-ner-hrl
Key                          | Status     |  |
-----------------------------+------------+--+-
bert.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

In [17]:
outputs_ner_classificator_1 = nlp(sport_news)
outputs_ner_classificator_2 = nlp(sport_news_2)
outputs_ner_classificator_3 = nlp(buisness_news_1)

In [19]:
outputs_ner_classificator_1

[{'entity': 'B-PER',
  'score': np.float32(0.9980514),
  'index': 1,
  'word': 'Dexter',
  'start': 0,
  'end': 6},
 {'entity': 'I-PER',
  'score': np.float32(0.99564064),
  'index': 2,
  'word': 'Lawrence',
  'start': 7,
  'end': 15},
 {'entity': 'B-ORG',
  'score': np.float32(0.9997501),
  'index': 9,
  'word': 'NFL',
  'start': 37,
  'end': 40},
 {'entity': 'B-ORG',
  'score': np.float32(0.9998068),
  'index': 22,
  'word': 'New',
  'start': 113,
  'end': 116},
 {'entity': 'I-ORG',
  'score': np.float32(0.99983),
  'index': 23,
  'word': 'York',
  'start': 117,
  'end': 121},
 {'entity': 'I-ORG',
  'score': np.float32(0.9997913),
  'index': 24,
  'word': 'Giants',
  'start': 122,
  'end': 128},
 {'entity': 'B-ORG',
  'score': np.float32(0.9998647),
  'index': 29,
  'word': 'Cincinnati',
  'start': 147,
  'end': 157},
 {'entity': 'I-ORG',
  'score': np.float32(0.9998641),
  'index': 30,
  'word': 'Bengal',
  'start': 158,
  'end': 164},
 {'entity': 'I-ORG',
  'score': np.float32(0.99984574),
  'index': 31,
  'word': '##s',
  'start': 164,
  'end': 165},
 {'entity': 'B-ORG',
  'score': np.float32(0.99978095),
  'index': 50,
  'word': 'Giants',
  'start': 226,
  'end': 232},
 {'entity': 'B-PER',
  'score': np.float32(0.9961959),
  'index': 55,
  'word': 'Lawrence',
  'start': 243,
  'end': 251},
 {'entity': 'B-ORG',
  'score': np.float32(0.9970181),
  'index': 68,
  'word': 'Pro',
  'start': 304,
  'end': 307},
 {'entity': 'I-ORG',
  'score': np.float32(0.99535453),
  'index': 69,
  'word': 'Bowl',
  'start': 308,
  'end': 312},
 {'entity': 'B-ORG',
  'score': np.float32(0.9997758),
  'index': 74,
  'word': 'Bengal',
  'start': 337,
  'end': 343},
 {'entity': 'I-ORG',
  'score': np.float32(0.99976414),
  'index': 75,
  'word': '##s',
  'start': 343,
  'end': 344},
 {'entity': 'B-LOC',
  'score': np.float32(0.9405113),
  'index': 109,
  'word': 'Pittsburgh',
  'start': 490,
  'end': 500},
 {'entity': 'B-PER',
  'score': np.float32(0.99858546),
  'index': 114,
  'word': 'Lawrence',
  'start': 521,
  'end': 529},
 {'entity': 'B-ORG',
  'score': np.float32(0.99978703),
  'index': 135,
  'word': 'Giants',
  'start': 620,
  'end': 626},
 {'entity': 'B-ORG',
  'score': np.float32(0.9996779),
  'index': 150,
  'word': 'NFL',
  'start': 691,
  'end': 694}]

In [23]:
for word in outputs_ner_classificator_1:
    print(f'Слово : {word['word']}, аббревиатура: {word['entity']}, уверенность {word['score']}')
print('*' * 36)
for word in outputs_ner_classificator_2:
    print(f'Слово : {word['word']}, аббревиатура: {word['entity']}, уверенность {word['score']}')
print('*' * 36)
for word in outputs_ner_classificator_3:
    print(f'Слово : {word['word']}, аббревиатура: {word['entity']}, уверенность {word['score']}')

Слово : Dexter, аббревиатура: B-PER, уверенность 0.9980514049530029
Слово : Lawrence, аббревиатура: I-PER, уверенность 0.9956406354904175
Слово : NFL, аббревиатура: B-ORG, уверенность 0.9997500777244568
Слово : New, аббревиатура: B-ORG, уверенность 0.999806821346283
Слово : York, аббревиатура: I-ORG, уверенность 0.9998300075531006
Слово : Giants, аббревиатура: I-ORG, уверенность 0.9997913241386414
Слово : Cincinnati, аббревиатура: B-ORG, уверенность 0.9998646974563599
Слово : Bengal, аббревиатура: I-ORG, уверенность 0.9998641014099121
Слово : ##s, аббревиатура: I-ORG, уверенность 0.9998457431793213
Слово : Giants, аббревиатура: B-ORG, уверенность 0.9997809529304504
Слово : Lawrence, аббревиатура: B-PER, уверенность 0.996195912361145
Слово : Pro, аббревиатура: B-ORG, уверенность 0.9970180988311768
Слово : Bowl, аббревиатура: I-ORG, уверенность 0.9953545331954956
Слово : Bengal, аббревиатура: B-ORG, уверенность 0.9997758269309998
Слово : ##s, аббревиатура: I-ORG, уверенность 0.9997641444206238
Слово : Pittsburgh, аббревиатура: B-LOC, уверенность 0.9405112862586975
Слово : Lawrence, аббревиатура: B-PER, уверенность 0.9985854625701904
Слово : Giants, аббревиатура: B-ORG, уверенность 0.9997870326042175
Слово : NFL, аббревиатура: B-ORG, уверенность 0.9996778964996338
************************************
Слово : UFC, аббревиатура: B-ORG, уверенность 0.999776303768158
Слово : Donald, аббревиатура: B-PER, уверенность 0.9999269247055054
Слово : Trump, аббревиатура: I-PER, уверенность 0.9998652935028076
Слово : White, аббревиатура: B-LOC, уверенность 0.9998154044151306
Слово : House, аббревиатура: I-LOC, уверенность 0.999782145023346
Слово : Trump, аббревиатура: B-PER, уверенность 0.9998879432678223
Слово : Miami, аббревиатура: B-LOC, уверенность 0.9999105930328369
Слово : UFC, аббревиатура: B-ORG, уверенность 0.9998264908790588
Слово : Dana, аббревиатура: B-PER, уверенность 0.9999048709869385
Слово : White, аббревиатура: I-PER, уверенность 0.9998446702957153
Слово : Iran, аббревиатура: B-LOC, уверенность 0.9998639822006226
Слово : UFC, аббревиатура: B-ORG, уверенность 0.9998462200164795
Слово : Derrick, аббревиатура: B-PER, уверенность 0.9999258518218994
Слово : Lewis, аббревиатура: I-PER, уверенность 0.9999018907546997
Слово : Josh, аббревиатура: B-PER, уверенность 0.9999253749847412
Слово : Ho, аббревиатура: I-PER, уверенность 0.99989914894104
Слово : ##kit, аббревиатура: I-PER, уверенность 0.9997910857200623
Слово : Dana, аббревиатура: B-PER, уверенность 0.9998788833618164
Слово : White, аббревиатура: I-PER, уверенность 0.9998213648796082
Слово : Trump, аббревиатура: B-PER, уверенность 0.9998970031738281
************************************
Слово : W, аббревиатура: B-ORG, уверенность 0.9997050166130066
Слово : ##al, аббревиатура: I-ORG, уверенность 0.9988682270050049
Слово : ##mar, аббревиатура: I-ORG, уверенность 0.9997102618217468
Слово : ##t, аббревиатура: I-ORG, уверенность 0.9997593760490417
Слово : U, аббревиатура: B-LOC, уверенность 0.9998598098754883
Слово : ., аббревиатура: I-LOC, уверенность 0.999815046787262
Слово : S, аббревиатура: I-LOC, уверенность 0.9998393058776855
Слово : ., аббревиатура: I-LOC, уверенность 0.9973626732826233
Слово : W, аббревиатура: B-ORG, уверенность 0.9986270666122437
Слово : ##al, аббревиатура: I-ORG, уверенность 0.9939221143722534
Слово : ##mar, аббревиатура: I-ORG, уверенность 0.9993897676467896
Слово : ##t, аббревиатура: I-ORG, уверенность 0.9994637370109558

In [14]:
tokenizer_2 = AutoTokenizer.from_pretrained("dslim/bert-base-NER")
model_2 = AutoModelForTokenClassification.from_pretrained("dslim/bert-base-NER")

nlp_classifier_2 = pipeline("ner", model=model_2, tokenizer=tokenizer_2, device = -1)
#example = "My name is Wolfgang and I live in Berlin"

#ner_results = nlp(example)
#print(ner_results)

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

BertForTokenClassification LOAD REPORT from: dslim/bert-base-NER
Key                      | Status     |  |
-------------------------+------------+--+-
bert.pooler.dense.weight | UNEXPECTED |  |
bert.pooler.dense.bias   | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

In [24]:
out_result_1 = nlp_classifier_2(sport_news)
out_result_2 = nlp_classifier_2(sport_news_2)
out_result_3 = nlp_classifier_2(buisness_news_1)

In [25]:
for word in out_result_1:
    print(f'Слово : {word['word']}, аббревиатура: {word['entity']}, уверенность {word['score']}')
print('*' * 36)
for word in out_result_2:
    print(f'Слово : {word['word']}, аббревиатура: {word['entity']}, уверенность {word['score']}')
print('*' * 36)
for word in out_result_3:
    print(f'Слово : {word['word']}, аббревиатура: {word['entity']}, уверенность {word['score']}')

Слово : Dexter, аббревиатура: B-PER, уверенность 0.9997252821922302
Слово : Lawrence, аббревиатура: I-PER, уверенность 0.9996718168258667
Слово : NFL, аббревиатура: B-ORG, уверенность 0.948975682258606
Слово : New, аббревиатура: B-ORG, уверенность 0.9992095232009888
Слово : York, аббревиатура: I-ORG, уверенность 0.9988686442375183
Слово : Giants, аббревиатура: I-ORG, уверенность 0.9989213943481445
Слово : Cincinnati, аббревиатура: B-ORG, уверенность 0.9993564486503601
Слово : Bengals, аббревиатура: I-ORG, уверенность 0.9988746047019958
Слово : Giants, аббревиатура: B-ORG, уверенность 0.9991901516914368
Слово : Lawrence, аббревиатура: B-PER, уверенность 0.9989284873008728
Слово : Pro, аббревиатура: B-MISC, уверенность 0.9983981251716614
Слово : Bowl, аббревиатура: I-MISC, уверенность 0.9987698197364807
Слово : Bengals, аббревиатура: B-ORG, уверенность 0.998553454875946
Слово : NFL, аббревиатура: B-MISC, уверенность 0.9912649989128113
Слово : Draft, аббревиатура: I-MISC, уверенность 0.988909900188446
Слово : Pittsburgh, аббревиатура: B-ORG, уверенность 0.9154354929924011
Слово : Lawrence, аббревиатура: B-PER, уверенность 0.9989860653877258
Слово : Giants, аббревиатура: B-ORG, уверенность 0.9988991022109985
Слово : NFL, аббревиатура: B-ORG, уверенность 0.6212357878684998
************************************
Слово : UFC, аббревиатура: B-ORG, уверенность 0.991629421710968
Слово : Donald, аббревиатура: B-PER, уверенность 0.9994195699691772
Слово : Trump, аббревиатура: I-PER, уверенность 0.9996609687805176
Слово : White, аббревиатура: B-LOC, уверенность 0.9995230436325073
Слово : House, аббревиатура: I-LOC, уверенность 0.9987882971763611
Слово : Trump, аббревиатура: B-PER, уверенность 0.9993340373039246
Слово : UFC, аббревиатура: B-MISC, уверенность 0.9898478388786316
Слово : 32, аббревиатура: I-MISC, уверенность 0.9928498268127441
Слово : ##7, аббревиатура: I-MISC, уверенность 0.9272019267082214
Слово : Miami, аббревиатура: B-LOC, уверенность 0.9993392825126648
Слово : UFC, аббревиатура: B-ORG, уверенность 0.9873161315917969
Слово : Dana, аббревиатура: B-PER, уверенность 0.9997679591178894
Слово : White, аббревиатура: I-PER, уверенность 0.999631404876709
Слово : Iran, аббревиатура: B-LOC, уверенность 0.9935613870620728
Слово : UFC, аббревиатура: B-ORG, уверенность 0.9975919723510742
Слово : Derrick, аббревиатура: B-PER, уверенность 0.9997668862342834
Слово : Lewis, аббревиатура: I-PER, уверенность 0.9997337460517883
Слово : Josh, аббревиатура: B-PER, уверенность 0.999804675579071
Слово : Ho, аббревиатура: I-PER, уверенность 0.9997408986091614
Слово : ##ki, аббревиатура: I-PER, уверенность 0.9950985312461853
Слово : ##t, аббревиатура: I-PER, уверенность 0.9695620536804199
Слово : UFC, аббревиатура: B-MISC, уверенность 0.9987892508506775
Слово : Freedom, аббревиатура: I-MISC, уверенность 0.9959238767623901
Слово : 250, аббревиатура: I-MISC, уверенность 0.948945939540863
Слово : Dana, аббревиатура: B-PER, уверенность 0.9997387528419495
Слово : White, аббревиатура: I-PER, уверенность 0.9996753931045532
Слово : Trump, аббревиатура: B-PER, уверенность 0.9994505047798157
************************************
Слово : W, аббревиатура: B-ORG, уверенность 0.9994028806686401
Слово : ##al, аббревиатура: I-ORG, уверенность 0.9876695275306702
Слово : ##mart, аббревиатура: I-ORG, уверенность 0.9984999895095825
Слово : U, аббревиатура: B-LOC, уверенность 0.9994068145751953
Слово : ., аббревиатура: I-LOC, уверенность 0.975191593170166
Слово : S, аббревиатура: I-LOC, уверенность 0.9976319074630737
Слово : ., аббревиатура: I-LOC, уверенность 0.7824875712394714
Слово : W, аббревиатура: B-ORG, уверенность 0.9993249177932739
Слово : ##al, аббревиатура: I-ORG, уверенность 0.9837526082992554
Слово : ##mart, аббревиатура: I-ORG, уверенность 0.9983590245246887

In [28]:
classifier_token_1 = pipeline("token-classification", model="dbmdz/bert-large-cased-finetuned-conll03-english", device = 0)

In [31]:
out_result_2_1 = classifier_token_1(sport_news)
out_result_2_2 = classifier_token_1(sport_news_2)
out_result_2_3 = classifier_token_1(buisness_news_1)

In [32]:
for word in out_result_2_1:
    print(f'Слово : {word['word']}, аббревиатура: {word['entity']}, уверенность {word['score']}')
print('*' * 36)
for word in out_result_2_2:
    print(f'Слово : {word['word']}, аббревиатура: {word['entity']}, уверенность {word['score']}')
print('*' * 36)
for word in out_result_2_3:
    print(f'Слово : {word['word']}, аббревиатура: {word['entity']}, уверенность {word['score']}')

Слово : Dexter, аббревиатура: I-PER, уверенность 0.9993250370025635
Слово : Lawrence, аббревиатура: I-PER, уверенность 0.9997685551643372
Слово : NFL, аббревиатура: I-ORG, уверенность 0.9440323114395142
Слово : New, аббревиатура: I-ORG, уверенность 0.9996452331542969
Слово : York, аббревиатура: I-ORG, уверенность 0.9995131492614746
Слово : Giants, аббревиатура: I-ORG, уверенность 0.9996441602706909
Слово : Cincinnati, аббревиатура: I-ORG, уверенность 0.9992889165878296
Слово : Bengals, аббревиатура: I-ORG, уверенность 0.9994373917579651
Слово : Giants, аббревиатура: I-ORG, уверенность 0.9996428489685059
Слово : Lawrence, аббревиатура: I-PER, уверенность 0.9997205138206482
Слово : Pro, аббревиатура: I-MISC, уверенность 0.9900422096252441
Слово : Bowl, аббревиатура: I-MISC, уверенность 0.9943777918815613
Слово : Bengals, аббревиатура: I-ORG, уверенность 0.9990736246109009
Слово : NFL, аббревиатура: I-MISC, уверенность 0.9955164790153503
Слово : Draft, аббревиатура: I-MISC, уверенность 0.9963889122009277
Слово : Pittsburgh, аббревиатура: I-LOC, уверенность 0.7169374227523804
Слово : Lawrence, аббревиатура: I-PER, уверенность 0.9997351765632629
Слово : Giants, аббревиатура: I-ORG, уверенность 0.999065101146698
Слово : NFL, аббревиатура: I-MISC, уверенность 0.7671090960502625
************************************
Слово : UFC, аббревиатура: I-ORG, уверенность 0.9993215799331665
Слово : Donald, аббревиатура: I-PER, уверенность 0.9990049004554749
Слово : Trump, аббревиатура: I-PER, уверенность 0.999596893787384
Слово : White, аббревиатура: I-LOC, уверенность 0.9988381266593933
Слово : House, аббревиатура: I-LOC, уверенность 0.9992929697036743
Слово : Trump, аббревиатура: I-PER, уверенность 0.9995627999305725
Слово : UFC, аббревиатура: I-MISC, уверенность 0.9111382961273193
Слово : 32, аббревиатура: I-MISC, уверенность 0.9555785059928894
Слово : ##7, аббревиатура: I-MISC, уверенность 0.7998640537261963
Слово : Miami, аббревиатура: I-LOC, уверенность 0.9994045495986938
Слово : UFC, аббревиатура: I-ORG, уверенность 0.998461127281189
Слово : Dana, аббревиатура: I-PER, уверенность 0.9992782473564148
Слово : White, аббревиатура: I-PER, уверенность 0.9994860887527466
Слово : Iran, аббревиатура: I-LOC, уверенность 0.9966959953308105
Слово : UFC, аббревиатура: I-ORG, уверенность 0.9989585876464844
Слово : Derrick, аббревиатура: I-PER, уверенность 0.999705970287323
Слово : Lewis, аббревиатура: I-PER, уверенность 0.9998339414596558
Слово : Josh, аббревиатура: I-PER, уверенность 0.9997217059135437
Слово : Ho, аббревиатура: I-PER, уверенность 0.9996496438980103
Слово : ##ki, аббревиатура: I-PER, уверенность 0.9935560822486877
Слово : ##t, аббревиатура: I-PER, уверенность 0.9896027445793152
Слово : UFC, аббревиатура: I-MISC, уверенность 0.9753004312515259
Слово : Freedom, аббревиатура: I-MISC, уверенность 0.9887146353721619
Слово : 250, аббревиатура: I-MISC, уверенность 0.8188710808753967
Слово : Dana, аббревиатура: I-PER, уверенность 0.9992520213127136
Слово : White, аббревиатура: I-PER, уверенность 0.9994751811027527
Слово : Trump, аббревиатура: I-PER, уверенность 0.9994692206382751
************************************
Слово : W, аббревиатура: I-ORG, уверенность 0.9990876913070679
Слово : ##al, аббревиатура: I-ORG, уверенность 0.993975818157196
Слово : ##mart, аббревиатура: I-ORG, уверенность 0.9988143444061279
Слово : U, аббревиатура: I-LOC, уверенность 0.9994822144508362
Слово : S, аббревиатура: I-LOC, уверенность 0.9993512034416199
Слово : W, аббревиатура: I-ORG, уверенность 0.9966109395027161
Слово : ##al, аббревиатура: I-ORG, уверенность 0.9964402318000793
Слово : ##mart, аббревиатура: I-ORG, уверенность 0.9983534812927246